M48
; DRILL file KiCad 10.0.1 date 2026-05-24T14:42:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-24T14:42:03-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X108.11Y-104.575
X113.89Y-104.575
T2
X77.5Y-73.0
X78.0Y-107.5
X119.0Y-73.0
X119.0Y-107.5
M30
